### ISSUE TITLE
Firefox release

### ISSUE THREAD

**Issue by DASPRiD** [ba32107/youtube-auto-proceed#8]
I was wondering if you could release this addon in the Firefox Addon store as well. Considering they use the same APIs nowadays, it shouldn't be a big issue I assume?

**Comment by ba32107** [comment]
Hi, sure, it should not be a big thing. I have very little free time these days, I'll try to squeeze this in at some point in the next month or so. Feel free to remind me here in a while, I'll do my best to get on it.

**Comment by ba32107** [comment]
@DASPRiD the Firefox version is now published for you:
https://addons.mozilla.org/en-GB/firefox/addon/youtube-auto-proceed-to-video/
